current_connection: ""
connections:
  my_db:
    name: my_db
    db_type: sqlite
    conn_string: ./db.sqlite
    queries: {}
    last_query:
      name: ""
      id: 0
      sql: ""
color_scheme: default
history:
  size: 0
default_row_limit: 1000
default_column_width: 15
