classic: false
blocks:
  - permission
  - user
  - group
  - size
  - date
  - name
color:
  when: always
  theme: default
date: "+%d %b %Y %H:%M"
icons:
  when: always
  theme: fancy
  separator: " "
indicators: true
sorting:
  column: name
  dir-grouping: first
